# Generated by Django 4.2.6 on 2023-12-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceh', models.CharField(max_length=5, verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Инв.№')),
                ('name_mashine', models.CharField(max_length=300, verbose_name='Наименование оборудования')),
                ('start_date', models.DateField(verbose_name='Дата выявления неполадки')),
                ('description', models.TextField(verbose_name='Описание неполадки')),
                ('photo_problem', models.ImageField(blank=True, upload_to='photo_problems', verbose_name='Фото неполадки')),
                ('comp_work', models.TextField(blank=True, verbose_name='Выполненые работы')),
                ('spare_parts', models.CharField(blank=True, max_length=300, verbose_name='Запчасти')),
                ('finish_date', models.DateField(blank=True, verbose_name='Дата устранения неполадки')),
                ('responsible', models.CharField(blank=True, max_length=50, verbose_name='Отвественный')),
                ('status', models.CharField(choices=[('OK', 'Все верно'), ('NO', 'Требует доработок')], max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('ceh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.ceh')),
            ],
            options={
                'verbose_name': 'Неполадки',
                'verbose_name_plural': 'Неполадки',
            },
        ),
        migrations.CreateModel(
            name='MashinsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Инв.№')),
                ('name_mashine', models.CharField(max_length=300, verbose_name='Наименование оборудования')),
                ('register_date', models.CharField(max_length=100, verbose_name='Дата ввода в эксплуатацию')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Изготовитель')),
                ('number_plant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заводской номер')),
                ('build_date', models.IntegerField(blank=True, null=True, verbose_name='Дата изготовления')),
                ('characteristics', models.TextField(verbose_name='Характеристики оборудования')),
                ('status', models.CharField(choices=[('OK', 'Все верно'), ('NO', 'Требует доработок')], max_length=10, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, upload_to='photo_mashins', verbose_name='Фото оборудования')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('ceh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.ceh')),
            ],
            options={
                'verbose_name': 'Ооборудование',
                'verbose_name_plural': 'Характеристики оборудования',
            },
        ),
        migrations.CreateModel(
            name='DTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Инв.№')),
                ('name_mashine', models.CharField(max_length=300, verbose_name='Наименование оборудования')),
                ('start_date', models.DateField(verbose_name='Дата проведения ДТО')),
                ('document', models.FileField(blank=True, null=True, upload_to='scan_card', verbose_name='Скан документа')),
                ('responsible', models.CharField(max_length=50, verbose_name='Ответственный')),
                ('status', models.CharField(choices=[('OK', 'Все верно'), ('NO', 'Требует доработок')], max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('ceh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.ceh')),
            ],
            options={
                'verbose_name': 'Карты ДТО',
                'verbose_name_plural': 'Карты ДТО',
            },
        ),
    ]
