# Generated by Django 4.2.6 on 2024-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceh', models.CharField(max_length=5, verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
            },
        ),
        migrations.CreateModel(
            name='DTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Инв.№')),
                ('name_mashine', models.CharField(default='-', max_length=300, verbose_name='Наименование оборудования')),
                ('ceh', models.CharField(choices=[('№ 1', '№ 1'), ('№ 2', '№ 2'), ('№ 3', '№ 3'), ('№ 4', '№ 4'), ('№ 5', '№ 5'), ('№ 6', '№ 6'), ('№ 7', '№ 7'), ('№ 8', '№ 8'), ('№ 9', '№ 9'), ('№ 10', '№ 10'), ('№ 11', '№ 11'), ('№ 21', '№ 21'), ('№ 16', '№ 16'), ('№ 17', '№ 17'), ('№ 18', '№ 18'), ('№ 19', '№ 19'), ('ЭПЦ', 'ЭПЦ'), ('Все цеха', 'Все цеха')], default='Цех № 1', max_length=10, verbose_name='Цех')),
                ('start_date', models.DateField(verbose_name='Дата начала ТОиР')),
                ('finish_date', models.DateField(verbose_name='Дата окончания ТОиР')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Предварительная дата ТОиР')),
                ('next_to', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=10, verbose_name='Принята карта ТОиР')),
                ('document', models.FileField(blank=True, null=True, upload_to='scan_card', verbose_name='Скан документа')),
                ('responsible', models.CharField(default='-', max_length=50, verbose_name='Ответственный')),
                ('status', models.CharField(choices=[('OK', 'Все верно'), ('NO', 'Требует доработок')], default='NO', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Карты ДТО',
                'verbose_name_plural': 'Карты ДТО',
            },
        ),
        migrations.CreateModel(
            name='MashinsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Инв.№')),
                ('name_mashine', models.CharField(max_length=300, verbose_name='Наименование оборудования')),
                ('ceh', models.CharField(choices=[('№ 1', '№ 1'), ('№ 2', '№ 2'), ('№ 3', '№ 3'), ('№ 4', '№ 4'), ('№ 5', '№ 5'), ('№ 6', '№ 6'), ('№ 7', '№ 7'), ('№ 8', '№ 8'), ('№ 9', '№ 9'), ('№ 10', '№ 10'), ('№ 11', '№ 11'), ('№ 21', '№ 21'), ('№ 16', '№ 16'), ('№ 17', '№ 17'), ('№ 18', '№ 18'), ('№ 19', '№ 19'), ('ЭПЦ', 'ЭПЦ'), ('Все цеха', 'Все цеха')], default='Цех № 1', max_length=10, verbose_name='Цех')),
                ('register_date', models.DateField(verbose_name='Дата регистрации')),
                ('to', models.IntegerField(default=2, verbose_name='Периодичность ТОиР (месяцев)')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Изготовитель')),
                ('number_plant', models.CharField(blank=True, max_length=100, verbose_name='Заводской номер')),
                ('build_date', models.CharField(blank=True, default='-', max_length=12, verbose_name='Дата изготовления')),
                ('characteristics', models.TextField(verbose_name='Характеристики оборудования')),
                ('status', models.CharField(choices=[('OK', 'Все верно'), ('NO', 'Требует доработок')], default='NO', max_length=10, verbose_name='Статус')),
                ('photo', models.FileField(blank=True, upload_to='photo_mashins', verbose_name='Фото оборудования')),
                ('nameplate', models.FileField(blank=True, null=True, upload_to='photo_mashins', verbose_name='Фото таблики оборудования')),
                ('form', models.FileField(blank=True, upload_to='form_mashins', verbose_name='Карта ТОиР')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Ооборудование',
                'verbose_name_plural': 'Характеристики оборудования',
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Инв.№')),
                ('name_mashine', models.CharField(default='-', max_length=300, verbose_name='Наименование оборудования')),
                ('ceh', models.CharField(choices=[('№ 1', '№ 1'), ('№ 2', '№ 2'), ('№ 3', '№ 3'), ('№ 4', '№ 4'), ('№ 5', '№ 5'), ('№ 6', '№ 6'), ('№ 7', '№ 7'), ('№ 8', '№ 8'), ('№ 9', '№ 9'), ('№ 10', '№ 10'), ('№ 11', '№ 11'), ('№ 21', '№ 21'), ('№ 16', '№ 16'), ('№ 17', '№ 17'), ('№ 18', '№ 18'), ('№ 19', '№ 19'), ('ЭПЦ', 'ЭПЦ'), ('Все цеха', 'Все цеха')], default='Цех № 1', max_length=10, verbose_name='Цех')),
                ('start_date', models.DateField(verbose_name='Дата выявления неполадки')),
                ('description', models.TextField(verbose_name='Описание неполадки')),
                ('photo_problem', models.ImageField(blank=True, upload_to='photo_problems', verbose_name='Фото неполадки')),
                ('comp_work', models.TextField(blank=True, verbose_name='Выполненые работы')),
                ('spare_parts', models.CharField(blank=True, max_length=300, verbose_name='Запчасти')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Дата устранения неполадки')),
                ('responsible', models.CharField(blank=True, max_length=50, verbose_name='Отвественный')),
                ('status', models.CharField(choices=[('OK', 'Все верно'), ('NO', 'Требует доработок')], default='NO', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Неполадки',
                'verbose_name_plural': 'Неполадки',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('ceh', models.CharField(choices=[('№ 1', '№ 1'), ('№ 2', '№ 2'), ('№ 3', '№ 3'), ('№ 4', '№ 4'), ('№ 5', '№ 5'), ('№ 6', '№ 6'), ('№ 7', '№ 7'), ('№ 8', '№ 8'), ('№ 9', '№ 9'), ('№ 10', '№ 10'), ('№ 11', '№ 11'), ('№ 21', '№ 21'), ('№ 16', '№ 16'), ('№ 17', '№ 17'), ('№ 18', '№ 18'), ('№ 19', '№ 19'), ('ЭПЦ', 'ЭПЦ'), ('Все цеха', 'Все цеха')], default='Цех № 1', max_length=10, verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddConstraint(
            model_name='mashinslist',
            constraint=models.UniqueConstraint(fields=('number',), name='person_number_unique'),
        ),
    ]
